### ISSUE TITLE
Need to handle the refresh token case

### ISSUE THREAD

**Issue by sudkumar** [tourepedia/tp-admin-ui#28]
When the user is actively using the system, the system should not logout the user in any case. Currently TTL for the token is 1 hour and TTL for refresh is 2 weeks. It means that, user is getting prompted to enter the passwords after 1 hour, even if the user is actively using the system.

**Comment by sudkumar** [comment]
Let's examine the different ways we can handle this case:

1. **Update the TTL for access token**
We can update the TTL for access token to some other values like 18 hr. This way, user can continuously work for 24 hr, which normally does not happen. So if the user logs in on day 1, on day 2, he/she will prompted to login again, which is fair enough.
**Pros**: Not much work is required for the development, only backend env variable needs to updated for access token TTL.
**Cons**: User may get logged out in the middle of the work if he/she logs in on a different time than normal work hours e.g. at mid night, then user may be prompted for login in between the work hours.

2. **Ask for refresh token for a 401 response**
We can request for a refresh token from an expired access token to get a new token when we get a 401 response for some request. This way, user will be able to stay logged in for 2w (TTL for refresh token) and then will asked for passwords again. We will need to exclude some api e.g. login, logout from this checkup.
**Pros**: User can stay logged in for a longer time period.
**Cons**: This will a bit more work and testing. The same can be achieved just by update the TTL for access token to same as refresh token TTL

3. **Prompt the user for password**
When we receive a 401 response, we can ask the user for a password again without redirecting to the login page.
**Pros**: User will never lose his/her work as he/she will be able to resume after entering the password
**Cons**: Much more stuff to implement and testing. Why do we have a refresh token in the first place!! 👎 

4. **Combine TTL increment and password prompt**
We can increase the access token TTL to around 9-10 hr (general working hours) and ask the user for password after it.

**Comment by khageshsaini** [comment]
I have changed the way we handled this is jobs. I have persisted the token in DB with some expiry(t). I make the JWT token using this with expiry of (x*t) where x is configurable. The user will get a prompt to extend the current session exactly x times after which he has no other option other than relogin again. It is highly likely that if the user is working and he gets a prompt to extend the session, he will do so. At a point where he can no longer save, the system just logs out the user.

**Comment by sudkumar** [comment]
@khageshsaini  Yeah. But prompting the user to extend the session while he/she is continuously using the system is not good (when we can automatically refresh the access token) and also, if the user is in middle of something and gets logged out, redirecting to login page can cause the work to be lost. We should prompt the user to reenter the password and let him/her continue work after successful authentication.

**Comment by musq** [comment]
Why do we have to logout the user after 1 day or n days? I don't see this behavior in Telegram (web), Github, Facebook, etc. Even Protonmail does not log you out unless you close the tab. Just keep them logged in forever like we do in a mobile app. **Logging out a user has nothing to do with security; it definitely infuriates you as a user.** Imagine how painful it would be if Github asked you to log in everyday?

Ideally, the access tokens should be stored in the database, so that they can be revoked to logout from other devices.

**Comment by sudkumar** [comment]
Hmm. Then we would need to implement the notification stuff for login on a new device along with showing a list of active sessions.

The tokens are always stored somewhere else you can not be revoked (logged out). In lumen-jwt, the token are stored in the CACHE_DRIVER. 

These two functionalities (notifications and active sessions) has to be implemented in any case whether or not we implement the refresh token functionality. So I think, we should do that thing only. 


FYI: Gmail does log out after some time. But they don't ask for OTPs after first log in on a device.

**Comment by sudkumar** [comment]
And BTW, **Not logging out has session compromisable security issues if the token revoking is not implemented.**

**Comment by musq** [comment]
Correct me if I'm wrong but I think Gmail logs you out when you are not using it, i.e. when you're in another tab, or not using the browser.

**Comment by sudkumar** [comment]
I don't know. It's quite random.

**Comment by sudkumar** [comment]
Updating TTL to 20hr for now 😈
